"""initial

Revision ID: b27265d6ce71
Revises: 
Create Date: 2023-12-24 21:53:42.296126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27265d6ce71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobTableAction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jobTableAction', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobType',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jobTypeName', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobWriteMode',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jobWriteMode', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('projectName', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeConditionType',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeConditionType', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timeConditionType')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('folder',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parentFolder_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('folderName', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobsScheduledType',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeConditionTypeId', sa.String(length=36), nullable=False),
    sa.Column('scheduledTypeName', sa.String(length=80), nullable=False),
    sa.Column('scheduledConditions', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['timeConditionTypeId'], ['timeConditionType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=False),
    sa.Column('jobTypeId', sa.String(length=36), nullable=False),
    sa.Column('parentJobTypeId', sa.String(length=36), nullable=False),
    sa.Column('createdUserId', sa.String(length=36), nullable=False),
    sa.Column('modifiedUserId', sa.String(length=36), nullable=False),
    sa.Column('parentJobId', sa.String(length=36), nullable=False),
    sa.Column('isCsv', sa.String(length=36), nullable=False),
    sa.Column('jobName', sa.String(length=80), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=False),
    sa.Column('modifiedDate', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createdUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['jobTypeId'], ['jobType.id'], ),
    sa.ForeignKeyConstraint(['modifiedUserId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parentJobTypeId'], ['jobType.id'], ),
    sa.PrimaryKeyConstraint('id', 'jobName')
    )
    op.create_table('jobProperty',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('jobId', sa.String(length=36), nullable=False),
    sa.Column('jobWriteModeId', sa.String(length=36), nullable=False),
    sa.Column('tableActionId', sa.String(length=36), nullable=False),
    sa.Column('sourceSqlScript', sa.String(length=80), nullable=False),
    sa.Column('targetTableName', sa.String(length=80), nullable=False),
    sa.Column('targetInsertHint', sa.String(length=80), nullable=False),
    sa.Column('beforeSqlScript', sa.String(length=80), nullable=False),
    sa.Column('afterSqlScript', sa.String(length=80), nullable=False),
    sa.Column('partition', sa.String(length=80), nullable=False),
    sa.Column('subPartition', sa.String(length=80), nullable=False),
    sa.Column('NoParallels', sa.String(length=80), nullable=False),
    sa.Column('fetchSize', sa.String(length=80), nullable=False),
    sa.Column('bufferSize', sa.String(length=80), nullable=False),
    sa.Column('commitSize', sa.String(length=80), nullable=False),
    sa.Column('inMemory', sa.String(length=80), nullable=False),
    sa.Column('priorityLevel', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['jobId'], ['job.id'], ),
    sa.ForeignKeyConstraint(['jobWriteModeId'], ['jobWriteMode.id'], ),
    sa.ForeignKeyConstraint(['tableActionId'], ['jobTableAction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobsScheduled',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scheduledTypeId', sa.String(length=36), nullable=False),
    sa.Column('jobId', sa.String(length=36), nullable=False),
    sa.Column('scheduledTime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['jobId'], ['job.id'], ),
    sa.ForeignKeyConstraint(['scheduledTypeId'], ['jobsScheduledType.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobsScheduled')
    op.drop_table('jobProperty')
    op.drop_table('job')
    op.drop_table('jobsScheduledType')
    op.drop_table('folder')
    op.drop_table('user')
    op.drop_table('timeConditionType')
    op.drop_table('project')
    op.drop_table('jobWriteMode')
    op.drop_table('jobType')
    op.drop_table('jobTableAction')
    # ### end Alembic commands ###
